export enum TipoTransaccion {
  RETIRO = 'RETIRO',
  DEPOSITO = 'DEPOSITO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  PAGO_SERVICIO = 'PAGO_SERVICIO',
  PRESTAMO = 'PRESTAMO',
  PAGO_PRESTAMO = 'PAGO_PRESTAMO',
}
